config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server.new, :at => "/resque"

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'omniauth'
  }

  authenticated :user do
    root to: redirect('/map') #to: 'drafts#map', :as => :authenticated_root
  end

  root to: 'explore#index', as: :unauthenticated_root
  get 'video', to: 'pages#video'

  resources :jobs, only: [:index, :create]
  resources :setups
  resources :uploads, except: [:new, :show, :delete]
  get 'map', to: 'drafts#map', as: :map
  resources :drafts
  resources :activities, :only => [:index, :show] do
    post '/recut' => 'activities#recut', as: :recut
  end

  resources :segment_efforts, only: [], path: 'efforts' do
    scope module: :segment_efforts do
      resources :drafts, only: [:index, :show]
    end
  end

  resource :slate, only: [:show] do
    get 'now', to: 'slates#now', as: :now
  end

  post 'sns' => 'sns#message', as: :sns
  get 'sns' => 'sns#message'

  resource :settings, only: [ :show ]

  namespace :api, :defaults => { :format => 'json' } do
    post '/dropbox_webhook' => 'dropbox_webhooks#webhook'
    get '/dropbox_webhook' => 'dropbox_webhooks#webhook'
  end

  get '/dropbox' => 'dropbox_browser#index', :as => :dropbox_browser
  resources :dropbox_events, :only => [:index, :create, :show]
end

app/models/setup.rb
# A setup contains the details of a camera setup.  This can include how the
# camera is mounted, whether the camera was attached to a Strava account.
class Setup < ActiveRecord::Base
  has_many :setup_uploads, dependent: :destroy
  has_many :video_uploads,
           through: :setup_uploads, source: :upload, class_name: 'VideoUpload'
  has_many :photo_uploads,
           through: :setup_uploads, source: :upload, class_name: 'PhotoUpload'
  has_many :videos, through: :video_uploads
  has_many :photos, through: :photo_uploads

  enum location: {
    static: 0,
    strava: 1
  }

  belongs_to :user

  validates :name, presence: true
  validates :range_m, numericality: { greater_than: 0 }
  validates_numericality_of :latitude, :longitude

  def self.with_videos_during(start_at, end_at)
    joins(:videos).merge(Video.during(start_at, end_at))
  end

  def self.with_photos_during(start_at, end_at)
    joins(:photos).merge(Photo.during(start_at, end_at))
  end

  def videos_during(start_at, end_at)
    videos.during(start_at, end_at)
  end

  def photos_during(start_at, end_at)
    photos.during(start_at, end_at)
  end

  def coords
    @coords ||= [latitude, longitude]
  end

  def coords_at(time)
    if strava?
      activity = user.activity_at(time)
      activity.coords_at(time) if activity
    else
      coords
    end
  end
end

app/controllers/setups_controller.rb
class SetupsController < LoggedInController
  before_action :find_setup, only: [:show, :edit, :update, :destroy]

  def new
    @setup = Setup.new
  end

  def index
    @setups = current_user.setups.order(updated_at: :desc)
  end

  def show
  end

  def edit
  end

  def update
    if @setup.update(setup_params)
      ajax_notice I18n.t('flash.activerecord.update.success')
      render json: @setup, status: :ok
    else
      render json: @setup, status: :unprocessable_entity
    end
  end

  def create
    @setup = Setup.create(setup_params)
    if @setup.persisted?
      ajax_notice I18n.t('flash.activerecord.create.success')
      render json: @setup, status: :ok
    else
      render json: @setup, status: :unprocessable_entity
    end
  end

  def destroy
    if @setup.destroy
      redirect_to setups_path, notice: 'Destroyed Setup'
    else
      redirect_to setup_path(@setup), alert: 'Could not destroy setup'
    end
  end

  protected

  def setup_params
    params
      .require(:setup)
      .permit(:name, :range_m, :latitude, :longitude, :location)
      .merge(user: current_user)
  end

  def find_setup
    @setup = Setup.find(params[:id])
  end
end

app/views/setups/_form.html.slim
= simple_form_for @setup do |f|
  = f.input :name
  = f.input :range_m, input_html: { min: 1, max: 30, step: 1 }
  div data-map-input=''
    a href='#' data-user-center-btn=''
      | Center on my location
    div data-user-center-status=''
      | Working
    div data-map=''
    = f.input :latitude, as: :hidden, input_html: { data: { latitude: '' } }
    = f.input :longitude, as: :hidden, input_html: { data: { longitude: '' } }
  = f.submit

app/views/setups/_setup.html.slim
.row
  .col-sm-6
    h4
      = link_to setup.name, setup_path(setup)
    p
      = link_to 'Delete', setup_path(setup), method: :delete

    table
      tr
        td
          | Last Updated
        td
          => time_ago_in_words(setup.updated_at)
          | ago
      tr
        td
          | Range (m)
        td
          = setup.range_m
      tr
        td
          | Lat,Lng
        td
          => setup.latitude
          | ,
          =< setup.longitude
      tr
        td
          | Location
        td
          = setup.location
  .col-sm-6
    = react_component 'SetupMap', setup: SetupSerializer.new(setup), readOnly: true

app/views/setups/edit.html.slim
= react_component 'ViewSetup', setup: SetupSerializer.new(@setup)

app/views/setups/index.html.slim
h1 Camera Setups
p
  = link_to 'New', new_setup_path, class: 'btn btn-primary'

= render @setups

app/views/setups/new.html.slim
= react_component 'ViewSetup', setup: SetupSerializer.new(@setup)